print("Hello World! I'm on Git now\n")
print("cool now it's interesting....\n")
print("ok i'm working on slave\n")
print("windows 10 working ")
print("now another test ")
print("on pipeline demo")
print("is this working")
